version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: sports-db
    environment:
      POSTGRES_DB: sports_management
      POSTGRES_USER: sports_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema:/docker-entrypoint-initdb.d
    networks:
      - sports-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sports_admin -d sports_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: sports-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sports-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (NestJS)
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: sports-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://sports_admin:${DB_PASSWORD:-dev_password}@postgres:5432/sports_management
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-dev_secret_change_in_production}
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - sports-network
    command: npm run start:dev

  # MinIO for file storage (alternative to AWS S3)
  minio:
    image: minio/minio:latest
    container_name: sports-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - sports-network
    command: server /data --console-address ":9001"

  # PgAdmin (Database Management UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sports-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sports.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - sports-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  sports-network:
    driver: bridge